
// This file is generated by Firebase Extensions.
'use server';

/**
 * @fileOverview This file is the entrypoint for Genkit's developer UI.
 *
 * It is not included in production builds.
 */
import {getFlows} from 'genkit';
// @ts-ignore
import * as flow from './flows/*';
export const f = getFlows(flow);
