-- InfraVision Database Setup Script
-- Generated by davidson.dev.br with AI assistance
-- Version: 1.3

-- Drop tables in reverse order of creation to handle dependencies
IF OBJECT_ID('dbo.Connections', 'U') IS NOT NULL DROP TABLE dbo.Connections;
IF OBJECT_ID('dbo.equipment_ports', 'U') IS NOT NULL DROP TABLE dbo.equipment_ports;
IF OBJECT_ID('dbo.port_types', 'U') IS NOT NULL DROP TABLE dbo.port_types;
IF OBJECT_ID('dbo.ConnectionTypes', 'U') IS NOT NULL DROP TABLE dbo.ConnectionTypes;
IF OBJECT_ID('dbo.child_items', 'U') IS NOT NULL DROP TABLE dbo.child_items;
IF OBJECT_ID('dbo.parent_items', 'U') IS NOT NULL DROP TABLE dbo.parent_items;
IF OBJECT_ID('dbo.ItemStatuses', 'U') IS NOT NULL DROP TABLE dbo.ItemStatuses;
IF OBJECT_ID('dbo.Models', 'U') IS NOT NULL DROP TABLE dbo.Models;
IF OBJECT_ID('dbo.Manufacturers', 'U') IS NOT NULL DROP TABLE dbo.Manufacturers;
IF OBJECT_ID('dbo.item_types', 'U') IS NOT NULL DROP TABLE dbo.item_types;
IF OBJECT_ID('dbo.item_typesEqp', 'U') IS NOT NULL DROP TABLE dbo.item_typesEqp;
IF OBJECT_ID('dbo.Rooms', 'U') IS NOT NULL DROP TABLE dbo.Rooms;
IF OBJECT_ID('dbo.Buildings', 'U') IS NOT NULL DROP TABLE dbo.Buildings;
IF OBJECT_ID('dbo.Users', 'U') IS NOT NULL DROP TABLE dbo.Users;
IF OBJECT_ID('dbo.AuditLog', 'U') IS NOT NULL DROP TABLE dbo.AuditLog;
IF OBJECT_ID('dbo.Sensors', 'U') IS NOT NULL DROP TABLE dbo.Sensors;
IF OBJECT_ID('dbo.Evidence', 'U') IS NOT NULL DROP TABLE dbo.Evidence;
IF OBJECT_ID('dbo.Incidents', 'U') IS NOT NULL DROP TABLE dbo.Incidents;
GO

-- Create Tables
CREATE TABLE Users (
    id NVARCHAR(100) PRIMARY KEY,
    email NVARCHAR(255) NOT NULL UNIQUE,
    displayName NVARCHAR(255),
    photoURL NVARCHAR(MAX),
    role NVARCHAR(50) NOT NULL,
    permissions NVARCHAR(MAX),
    accessiblebuilding_ids NVARCHAR(MAX),
    lastLoginAt DATETIME2 NOT NULL,
    preferences NVARCHAR(MAX),
    is_test_data BIT NOT NULL DEFAULT 0
);
GO

CREATE TABLE Buildings (
    id NVARCHAR(50) PRIMARY KEY,
    name NVARCHAR(100) NOT NULL UNIQUE,
    address NVARCHAR(255),
    is_test_data BIT NOT NULL DEFAULT 0
);
GO

CREATE TABLE Rooms (
    id NVARCHAR(50) PRIMARY KEY,
    name NVARCHAR(100) NOT NULL,
    building_id NVARCHAR(50) NOT NULL,
    largura FLOAT,
    width_m FLOAT,
    tile_width_cm FLOAT,
    tile_height_cm FLOAT,
    xAxisNaming NVARCHAR(20) DEFAULT 'alpha',
    yAxisNaming NVARCHAR(20) DEFAULT 'numeric',
    backgroundImageUrl NVARCHAR(MAX),
    backgroundScale FLOAT,
    backgroundPosX FLOAT,
    backgroundPosY FLOAT,
    is_test_data BIT NOT NULL DEFAULT 0,
    FOREIGN KEY (building_id) REFERENCES Buildings(id) ON DELETE CASCADE
);
GO

CREATE TABLE item_types (
    id NVARCHAR(50) PRIMARY KEY,
    name NVARCHAR(100) NOT NULL UNIQUE,
    category NVARCHAR(100) NOT NULL,
    defaultwidth_m FLOAT NOT NULL,
    default_height_m FLOAT NOT NULL,
    icon_name NVARCHAR(50),
    can_have_children BIT NOT NULL DEFAULT 0,
    is_resizable BIT NOT NULL DEFAULT 1,
    status NVARCHAR(50) NOT NULL DEFAULT 'active',
    is_test_data BIT NOT NULL DEFAULT 0,
    default_color NVARCHAR(50)
);
GO

CREATE TABLE item_typesEqp (
    id NVARCHAR(50) PRIMARY KEY,
    name NVARCHAR(100) NOT NULL UNIQUE,
    category NVARCHAR(100) NOT NULL,
    defaultwidth_m FLOAT NOT NULL,
    default_height_m FLOAT NOT NULL,
    icon_name NVARCHAR(50),
    status NVARCHAR(50) NOT NULL DEFAULT 'active',
    is_test_data BIT NOT NULL DEFAULT 0,
    default_color NVARCHAR(50)
);
GO

CREATE TABLE Manufacturers (
    id NVARCHAR(50) PRIMARY KEY,
    name NVARCHAR(100) NOT NULL UNIQUE,
    is_test_data BIT NOT NULL DEFAULT 0
);
GO

CREATE TABLE Models (
    id NVARCHAR(50) PRIMARY KEY,
    name NVARCHAR(100) NOT NULL,
    manufacturer_id NVARCHAR(50) NOT NULL,
    portConfig NVARCHAR(MAX),
    tamanho_u INT,
    is_test_data BIT NOT NULL DEFAULT 0,
    FOREIGN KEY (manufacturer_id) REFERENCES Manufacturers(id) ON DELETE CASCADE,
    UNIQUE (name, manufacturer_id)
);
GO

CREATE TABLE ItemStatuses (
    id NVARCHAR(50) PRIMARY KEY,
    name NVARCHAR(100) NOT NULL UNIQUE,
    description NVARCHAR(255),
    color NVARCHAR(20) NOT NULL,
    isArchived BIT NOT NULL DEFAULT 0,
    isDefault BIT NOT NULL DEFAULT 0
);
GO

CREATE TABLE parent_items (
    id NVARCHAR(50) PRIMARY KEY,
    label NVARCHAR(100) NOT NULL,
    x INT NOT NULL DEFAULT 0,
    y INT NOT NULL DEFAULT 0,
    width FLOAT NOT NULL DEFAULT 0.6,
    height FLOAT NOT NULL DEFAULT 1.0,
    type NVARCHAR(50) NOT NULL,
    status NVARCHAR(50) NOT NULL,
    room_id NVARCHAR(50),
    serial_number NVARCHAR(100),
    brand NVARCHAR(100),
    tag NVARCHAR(100),
    isTagEligible BIT,
    ownerEmail NVARCHAR(255),
    dataSheetUrl NVARCHAR(MAX),
    description NVARCHAR(MAX),
    imageUrl NVARCHAR(MAX),
    modelo NVARCHAR(100),
    preco FLOAT,
    trellisId NVARCHAR(100),
    tamanho_u INT,
    potencia_w INT,
    color NVARCHAR(50),
    is_test_data BIT NOT NULL DEFAULT 0,
    FOREIGN KEY (room_id) REFERENCES Rooms(id) ON DELETE SET NULL,
    FOREIGN KEY (status) REFERENCES ItemStatuses(id)
);
GO

CREATE TABLE child_items (
    id NVARCHAR(50) PRIMARY KEY,
    label NVARCHAR(100) NOT NULL,
    parent_id NVARCHAR(50) NOT NULL,
    type NVARCHAR(50) NOT NULL,
    status NVARCHAR(50) NOT NULL,
    serial_number NVARCHAR(100),
    brand NVARCHAR(100),
    tag NVARCHAR(100),
    isTagEligible BIT,
    ownerEmail NVARCHAR(255),
    dataSheetUrl NVARCHAR(MAX),
    description NVARCHAR(MAX),
    imageUrl NVARCHAR(MAX),
    modelo NVARCHAR(100),
    preco FLOAT,
    trellisId NVARCHAR(100),
    tamanho_u INT,
    posicao_u INT,
    is_test_data BIT NOT NULL DEFAULT 0,
    FOREIGN KEY (parent_id) REFERENCES parent_items(id) ON DELETE CASCADE,
    FOREIGN KEY (status) REFERENCES ItemStatuses(id)
);
GO

CREATE TABLE port_types (
    id NVARCHAR(50) PRIMARY KEY,
    name NVARCHAR(100) NOT NULL UNIQUE,
    description NVARCHAR(255),
    isDefault BIT NOT NULL DEFAULT 0
);
GO

CREATE TABLE ConnectionTypes (
    id NVARCHAR(50) PRIMARY KEY,
    name NVARCHAR(100) NOT NULL UNIQUE,
    description NVARCHAR(255),
    isDefault BIT NOT NULL DEFAULT 0
);
GO

CREATE TABLE equipment_ports (
    id NVARCHAR(50) PRIMARY KEY,
    childItemId NVARCHAR(50) NOT NULL,
    port_typeId NVARCHAR(50) NOT NULL,
    label NVARCHAR(100) NOT NULL,
    status NVARCHAR(50) NOT NULL DEFAULT 'down',
    connectedToPortId NVARCHAR(50),
    notes NVARCHAR(MAX),
    FOREIGN KEY (childItemId) REFERENCES child_items(id) ON DELETE CASCADE,
    FOREIGN KEY (port_typeId) REFERENCES port_types(id),
    FOREIGN KEY (connectedToPortId) REFERENCES equipment_ports(id),
    UNIQUE(connectedToPortId)
);
GO

CREATE TABLE Connections (
    id NVARCHAR(50) PRIMARY KEY,
    portA_id NVARCHAR(50) NOT NULL,
    portB_id NVARCHAR(50) NOT NULL,
    connectionTypeId NVARCHAR(50) NOT NULL,
    label NVARCHAR(255),
    status NVARCHAR(50) NOT NULL DEFAULT 'active',
    is_test_data BIT NOT NULL DEFAULT 0,
    FOREIGN KEY (portA_id) REFERENCES equipment_ports(id),
    FOREIGN KEY (portB_id) REFERENCES equipment_ports(id),
    FOREIGN KEY (connectionTypeId) REFERENCES ConnectionTypes(id),
    UNIQUE (portA_id),
    UNIQUE (portB_id)
);
GO

CREATE TABLE AuditLog (
    id INT IDENTITY(1,1) PRIMARY KEY,
    timestamp DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    user_id NVARCHAR(100) NOT NULL,
    userDisplayName NVARCHAR(255),
    action NVARCHAR(255) NOT NULL,
    entity_type NVARCHAR(50),
    entity_id NVARCHAR(100),
    details NVARCHAR(MAX)
);
GO

CREATE TABLE Incidents (
    id NVARCHAR(50) PRIMARY KEY,
    description NVARCHAR(MAX) NOT NULL,
    severity NVARCHAR(50) NOT NULL CHECK (severity IN ('critical', 'high', 'medium', 'low')),
    status NVARCHAR(50) NOT NULL CHECK (status IN ('open', 'investigating', 'closed')),
    detectedAt DATETIME2 NOT NULL,
    resolvedAt DATETIME2,
    entity_type NVARCHAR(50),
    entity_id NVARCHAR(100)
);
GO

CREATE TABLE Evidence (
    id NVARCHAR(50) PRIMARY KEY,
    incidentId NVARCHAR(50) NOT NULL,
    timestamp DATETIME2 NOT NULL,
    type NVARCHAR(50) NOT NULL,
    data NVARCHAR(MAX) NOT NULL,
    FOREIGN KEY (incidentId) REFERENCES Incidents(id) ON DELETE CASCADE
);
GO

CREATE TABLE Sensors (
    id NVARCHAR(50) PRIMARY KEY,
    itemId NVARCHAR(50) NOT NULL,
    type NVARCHAR(100) NOT NULL,
    value FLOAT,
    unit NVARCHAR(20),
    lastReading DATETIME2,
    FOREIGN KEY (itemId) REFERENCES parent_items(id) ON DELETE CASCADE
);
GO

-- Insert Initial Data
INSERT INTO Users (id, email, displayName, photoURL, role, permissions, accessiblebuilding_ids, lastLoginAt, is_test_data) 
VALUES ('dev_user', 'dev@dev.com', 'Desenvolvedor Padrão', NULL, 'developer', '["*"]', '[]', GETUTCDATE(), 1);
GO

INSERT INTO Buildings (id, name, address, is_test_data)
VALUES ('B_initial', 'DC-TESTE', 'Local de Testes Iniciais', 1);
GO

INSERT INTO Rooms (id, name, building_id, is_test_data)
VALUES ('R_initial', 'SALA-TESTE', 'B_initial', 1);
GO

INSERT INTO ItemStatuses (id, name, description, color, isArchived, isDefault)
VALUES 
('draft', 'Rascunho', 'Item recém-criado, aguardando submissão.', 'amber', 0, 1),
('pending_approval', 'Pendente', 'Item submetido, aguardando aprovação.', 'yellow', 0, 1),
('active', 'Ativo', 'Item aprovado e operacional.', 'green', 0, 1),
('maintenance', 'Manutenção', 'Item em manutenção, temporariamente indisponível.', 'orange', 0, 1),
('decommissioned', 'Descomissionado', 'Item removido e movido para a lixeira.', 'gray', 1, 1);
GO

INSERT INTO port_types (id, name, description, isDefault)
VALUES
('port_rj45', 'RJ45', 'Conector de rede padrão para cabos UTP (par trançado).', 1),
('port_sfp', 'SFP/SFP+', 'Conector para transceptores ópticos ou de cobre de pequena dimensão.', 1);
GO

INSERT INTO ConnectionTypes (id, name, description, isDefault)
VALUES
('conn_utp', 'Dados UTP', 'Conexão de dados via cabo de par trançado.', 1),
('conn_fibra', 'Fibra Óptica', 'Conexão de dados via fibra óptica monomodo ou multimodo.', 1);
GO


PRINT 'InfraVision Database Setup Completed Successfully.';
GO
